# Introduction to Pandas

## What is Pandas?
Pandas is an open-source Python library used for data manipulation, analysis and cleaning. It provides fast and flexible tools to work with tabular data, similar to spreadsheets or SQL tables.

Importing pandas

In [4]:
import pandas as pd

### Series

A **Series** is a one-dimensional labeled array in Pandas that can store data of any type, such as integers, strings, or floating-point numbers.

You can think of a Series as a **single column of a DataFrame**.

```python
import pandas as pd
sales = pd.Series([25, 15, 30, 20])
print(sales)
```

**Output:**

```text
0    25
1    15
2    30
3    20
dtype: int64
```

A column from the `coffee` DataFrame is also a Series:

```python
coffee["Units Sold"]
```

Here, `Units Sold` is a Pandas Series containing all the values from that column.

# DataFrame

A **Dataframe** is a 2D tabular structure consists of rows and columns.

You can create a dataframe using the following code and pass a nested list as an argument

In [ ]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
df

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  18

The numbers 0, 1, and 2 on the left side of the rows are called indices (or the index of the DataFrame). By default, Pandas assigns integer indices starting from 0.

We can rename the index by using the index parameter while creating the DataFrame.

In [ ]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]],index=['A','B','C','D','E','F'])
df

    0   1   2
A   1   2   3
B   4   5   6
C   7   8   9
D  10  11  12
E  13  14  15
F  16  17  18

**Using** df.head(), we can view the first five rows of a DataFrame. By default, it returns the first 5 rows.

In [ ]:
df.head()

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

**You** can also pass an argument to df.head() to specify the number of rows you want to view.

In [ ]:
df.head(10)

    0   1   2
A   1   2   3
B   4   5   6
C   7   8   9
D  10  11  12
E  13  14  15
F  16  17  18

**You** can also rename the columns of a DataFrame using the columns argument while creating the DataFrame.

In [5]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]],columns=['X','Y','Z'])
df.head()

    X   Y   Z
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

Now let's rename both the **rows** and **columns** while creating the DataFrame

### `type()` Function

The `type()` function is used to determine the data type of an object.

```python
type(df)
```

**Output:**

```text
pandas.core.frame.DataFrame
```

A single column of a DataFrame is a Pandas Series:

```python
type(df["X"])
```

**Output:**

```text
pandas.core.series.Series
```

**Example Series:**

```python
df["X"]
```

**Output:**

```text
0    1
1    4
2    7
3   10
4   13
5   16
Name: X, dtype: int64
```

Here, `df` is a DataFrame, while `df["X"]` is a Series.

In [6]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]],index=['A','B','C','D','E','F'],columns=['X','Y','Z'])
df.head()

    X   Y   Z
A   1   2   3
B   4   5   6
C   7   8   9
D  10  11  12
E  13  14  15

You can view the row indices and column labels using the index and columns attributes of a DataFrame.

In [ ]:
df.index

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [ ]:
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

You can use the info() method to get information about a DataFrame. It also shows the memory usage.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, A to F
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       6 non-null      int64
 1   Y       6 non-null      int64
 2   Z       6 non-null      int64
dtypes: int64(3)
memory usage: 364.0+ bytes

To get statistical info about a DataFrawe we can use describe() method

In [ ]:
df.describe()

               X          Y          Z
count   6.000000   6.000000   6.000000
mean    8.500000   9.500000  10.500000
std     5.612486   5.612486   5.612486
min     1.000000   2.000000   3.000000
25%     4.750000   5.750000   6.750000
50%     8.500000   9.500000  10.500000
75%    12.250000  13.250000  14.250000
max    16.000000  17.000000  18.000000

We can use the nunique() method to find the number of unique values in a column.

In [ ]:
df.nunique()

X    6
Y    6
Z    6
dtype: int64

In [ ]:
df['X'].unique()

array([ 1,  4,  7, 10, 13, 16])

The shape attribute tells us the no of rows and columns in a DataFrame

In [ ]:
df.shape

(6, 3)

The size attribute tells us the total number of items in a DataFrame

In [ ]:
df.size

18

We can use tail() method to view the last rows of a DataFrame.It works similarly to the head() method

In [ ]:
df.tail()

    X   Y   Z
B   4   5   6
C   7   8   9
D  10  11  12
E  13  14  15
F  16  17  18