## This notebook is the continuation of the "Intro_to_Pandas" notebook.

Loading in DataFrames from Files

In [ ]:
import pandas as pd

We can use either the file path or the URL of a CSV file to load it into a DataFrame.

In [ ]:
coffee=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/a45fad77f8791a639f0de52a7b169cb65a1482a2/warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

We can use `sample()` method to view random rows.
You can pass an argument to specify the number of rows.

In [ ]:
coffee.sample(4)

         Day Coffee Type  Units Sold
11  Saturday       Latte          35
3    Tuesday       Latte          20
9     Friday       Latte          35
6   Thursday    Espresso          40

We can also use the random_state argument. It allows us to get the same random sample every time we run the code, returning the same rows on each run.

In [ ]:
coffee.sample(4,random=10)

         Day Coffee Type  Units Sold
3    Tuesday       Latte          20
7   Thursday       Latte          30
12    Sunday    Espresso          45
6   Thursday    Espresso          40

### Accessing Entire Columns

---



We can use indexing (`[]`) or the dot (`.`) operator to access an entire column in a DataFrame.

#### Using Indexing

```python
coffee['Day']
```

#### Using the Dot Operator

```python
coffee.Day
```

Both statements return the entire **`Day`** column.

> **Note:** The dot operator only works when the column name is a valid Python identifier (e.g., no spaces or special characters). Using indexing (`[]`) is generally more flexible and recommended.

In [ ]:
coffee.Day

Day
Monday          Monday
Monday          Monday
Tuesday        Tuesday
Tuesday        Tuesday
Wednesday    Wednesday
Wednesday    Wednesday
Thursday      Thursday
Thursday      Thursday
Friday          Friday
Friday          Friday
Saturday      Saturday
Saturday      Saturday
Sunday          Sunday
Sunday          Sunday
Name: Day, dtype: object

## Accessing Elements in a DataFrame

---



There are two main ways to access elements in a DataFrame:

1. `loc[]`
2. `iloc[]`

### `loc[]`

The `loc[]` method uses **row labels** and **column labels** to access data.

### `iloc[]`

The `iloc[]` method uses **integer-based indices** (row and column positions) to access data.

### Using `loc[]`

In [ ]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [ ]:
coffee.loc[[0,1,6]]

        Day Coffee Type  Units Sold
0    Monday    Espresso          25
1    Monday       Latte          15
6  Thursday    Espresso          40

In [ ]:
coffee.loc[0:6] #Using slicing

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40

### Let's use labels to access data
`loc[]` uses the following format `coffee.loc[Rows,Columns]`.

We can also pass a list as an argument with labels

In [ ]:
coffee.loc[[0,1,2],["Day","Units Sold"]]

       Day  Units Sold
0   Monday          25
1   Monday          15
2  Tuesday          30

### Using `iloc[]`

The `iloc[]` method uses the following syntax:

```python
coffee.iloc[rows, columns]
```

Unlike `loc[]`, which uses row and column labels, `iloc[]` only accepts **integer-based indices** as arguments.

#### Example

```python
coffee.iloc[0, 1]
```

This returns the value located in the first row (`0`) and the second column (`1`).

We can also pass a list of indices to access multiple rows and columns:

```python
coffee.iloc[[0, 2], [1, 2]]
```

This returns the values from rows at indices `0` and `2` and columns at indices `1` and `3`.

In [ ]:
coffee.iloc[[0, 2], [1, 2]]

  Coffee Type  Units Sold
0    Espresso          25
2    Espresso          30

In [ ]:
coffee.iloc[0:6,1] #Using slicing

0    Espresso
1       Latte
2    Espresso
3       Latte
4    Espresso
5       Latte
Name: Coffee Type, dtype: object

You can set the index of the DataFrame using the `index()` method

In [ ]:
coffee.index=coffee["Day"]
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [ ]:
coffee.index.name

In [ ]:
coffee.loc["Monday":"Wednesday","Coffee Type"] # Here, "Monday" and "Wednesday" are row labels because "Day" was set as the index.

Day
Monday       Espresso
Monday          Latte
Tuesday      Espresso
Tuesday         Latte
Wednesday    Espresso
Wednesday       Latte
Name: Coffee Type, dtype: object

We can reset the indices using the `reset_index()` method:
 ```python
coffee = coffee.reset_index()
```

In [ ]:
coffee = coffee.reset_index(drop=True)

In [ ]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

###Setting the DataFrame values using `loc[]` and `iloc`.

In [ ]:
coffee.loc[0,"Units Sold"]=17
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          17
1     Monday       Latte          17
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
coffee.iloc[1,2]=17
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          17
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

### Accessing a Single Element

We can use the `at()` and `iat()` methods to access a single element in a DataFrame.

- `at()` is analogous to `loc[]` and uses **row and column labels**.
- `iat()` is analogous to `iloc[]` and uses **integer-based indices**.

Unlike `loc[]` and `iloc[]`, these methods can only access a single element at a time.

#### Examples

Using `at()`:

```python
coffee.at['Monday', 'Coffee Type']
```

Using `iat()`:

```python
coffee.iat[0, 1]
```

Both statements return a single value from the DataFrame.

In [ ]:
coffee.at[0,"Day"]

'Monday'

In [ ]:
coffee.at[0:5,"Day"] # This raises an error because at() can only access a single element, not multiple rows.

KeyError: slice(0, 5, None)

## Sorting Data

We can use the `sort_values()` method to sort a DataFrame based on one or more columns.

By default, the data is sorted in **ascending order**. To sort in **descending order**, pass `ascending=False` as an argument.

### Example

```python
coffee.sort_values("Units Sold")
```

This sorts the DataFrame by the `Units Sold` column in ascending order.

### Descending Order

```python
coffee.sort_values("Units Sold", ascending=False)
```

This sorts the DataFrame by the `Units Sold` column in descending order.

In [ ]:
coffee.sort_values("Units Sold")

          Day Coffee Type  Units Sold
0      Monday    Espresso          17
1      Monday       Latte          17
3     Tuesday       Latte          20
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

### Sorting by Multiple Columns

We can sort a DataFrame using multiple columns by passing a list of column names to the `by` parameter.

```python
coffee.sort_values(
    by=["Coffee Type", "Units Sold"],
    ascending=[True, False]
)
```

In this example:

- `Coffee Type` is sorted in ascending order.
- `Units Sold` is sorted in descending order within each coffee type.

---

### Sorting and Slicing

We can combine sorting with slicing to view only a subset of the sorted data.

```python
coffee.sort_values(
    "Units Sold",
    ascending=False
)
```

This returns the top 5 rows with the highest values in the `Units Sold` column.

---

### Sorting by Multiple Columns and Slicing

```python
coffee.sort_values(
    ["Coffee Type", "Units Sold"],
    ascending=[True, False]
)
```

This first sorts the DataFrame by `Coffee Type` and `Units Sold`, then returns the first 10 rows of the sorted DataFrame.

In [ ]:
coffee.sort_values(
    by=["Coffee Type", "Units Sold"]
)

          Day Coffee Type  Units Sold
0      Monday    Espresso          17
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
1      Monday       Latte          17
3     Tuesday       Latte          20
5   Wednesday       Latte          25
7    Thursday       Latte          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35

In [ ]:
coffee.sort_values(
    ["Coffee Type", "Units Sold"],
    ascending=[True, False]
)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
2     Tuesday    Espresso          30
0      Monday    Espresso          17
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
7    Thursday       Latte          30
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          17

## Iterating Through Rows

We can use the `iterrows()` method to iterate through the rows of a DataFrame.

The method returns:
- The row index.
- The row data as a Pandas Series.

### Example

```python
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print("\n")
```

In the above example:

- `index` stores the index label of the current row.
- `row` stores the row data as a Series.
- The loop iterates through each row of the DataFrame one at a time.

### Accessing Individual Values

We can access values from the current row using column labels.

```python
for index, row in coffee.iterrows():
    print(row["Coffee Type"])
    print(row["Units Sold"])
```

This prints the values of the `Coffee Type` and `Units Sold` columns for each row.

In [ ]:
for index,row in coffee.iterrows():
  print(index)
  print(row)
  print("\n\n")

0
Day              Monday
Coffee Type    Espresso
Units Sold           17
Name: 0, dtype: object



1
Day            Monday
Coffee Type     Latte
Units Sold         17
Name: 1, dtype: object



2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object



3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object



4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object



5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object



6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object



7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object



8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object



9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object



10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object



11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object



12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object



13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

In [ ]:
for index, row in coffee.iterrows():
    print(row["Coffee Type"])
    print(row["Units Sold"])

Espresso
17
Latte
17
Espresso
30
Latte
20
Espresso
35
Latte
25
Espresso
40
Latte
30
Espresso
45
Latte
35
Espresso
45
Latte
35
Espresso
45
Latte
35