# Pandas(Part-2)

In [1]:
import pandas as pd

In [ ]:
bios=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/a45fad77f8791a639f0de52a7b169cb65a1482a2/data/bios.csv')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

#Filtering Data

We can pass Boolean conditions to the `loc[]` method to filter rows in a DataFrame.

The condition generates a Boolean Series containing `True` and `False` values. Rows corresponding to `True` are selected, while rows corresponding to `False` are excluded.

In [ ]:
bios.loc[bios['height_cm']>180]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN
25,26,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145465,149192,Stanislav Galiyev,1992-01-17,Moskva (Moscow),Moskva,RUS,ROC,188.0,82.0,NaN
145466,149193,Mikkel Aagaard,1995-10-18,Frederikshavn,Nordjylland,DEN,Denmark,184.0,81.0,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145473,149200,Toms Andersons,1993-11-25,Rīga,Rīga,LAT,Latvia,185.0,86.0,NaN
145494,149221,George Wright,1890-07-21,Toronto,Ontario,CAN,Canada,183.0,NaN,1973-01-28

In [ ]:
bios.loc[bios['height_cm']>210,['name','height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5572          Santiago Aldama      213.0
5583     Paulinho Villas Boas      217.0
5599        Vladimir Andreyev      215.0
5609          Franjo Arapović      211.0
...                       ...        ...
140298       Aaron Geramipoor      214.0
141018          Yuta Watanabe      215.0
142044          Jahlil Okafor      211.0
142930             Mike Tobey      213.0
143712           JaVale McGee      213.0

[150 rows x 2 columns]

### Using Multiple Conditions with `&` and `|`

We can combine multiple Boolean conditions using the following operators:

- `&` → Logical AND
- `|` → Logical OR

When using multiple conditions, each condition must be enclosed in parentheses.

### Using `&` (AND)

```python
coffee.loc[
    (coffee["Units Sold"] > 50) &
    (coffee["Coffee Type"] == "Latte")
]
```

This returns rows where:

- `Units Sold` is greater than 50, **and**
- `Coffee Type` is `"Latte"`.

### Using `|` (OR)

```python
coffee.loc[
    (coffee["Units Sold"] > 50) |
    (coffee["Coffee Type"] == "Latte")
]
```

This returns rows where:

- `Units Sold` is greater than 50, **or**
- `Coffee Type` is `"Latte"`.

### Combining Multiple Conditions

```python
coffee.loc[
    ((coffee["Units Sold"] > 50) &
     (coffee["Coffee Type"] == "Latte")) |
    (coffee["Price Per Unit"] > 4)
]
```

This returns rows where:

- Both `Units Sold > 50` and `Coffee Type == "Latte"`, **or**
- `Price Per Unit > 4`.

> **Note:** Use `&` and `|` for DataFrame filtering instead of Python's `and` and `or`. Also, remember to wrap each condition in parentheses.

In [ ]:
bios.loc[(bios['height_cm']>210) & (bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5681,5704,Walt Bellamy,1937-07-24,New Bern,North Carolina,USA,United States,211.0,98.0,2013-11-02
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5894,5919,Mel Counts,1941-10-16,Coos Bay,Oregon,USA,United States,213.0,102.0,NaN
6106,6133,Marc Freiberger,1928-11-27,Amarillo,Texas,USA,United States,211.0,98.0,2005-06-29
6281,6309,Darrall Imhoff,1938-10-11,San Gabriel,California,USA,United States,211.0,98.0,2017-06-30
6379,6410,Joe Kleine,1962-01-04,Colorado Springs,Colorado,USA,United States,211.0,122.0,NaN
6393,6424,Jon Koncak,1963-05-17,Cedar Rapids,Iowa,USA,United States,213.0,113.0,NaN
6442,6473,Christian Laettner,1969-08-17,Angola,New York,USA,United States,211.0,107.0,NaN
6615,6648,Tom McMillen,1952-05-26,Mansfield,Pennsylvania,USA,United States,212.0,95.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
7012,7048,Daniel Santiago,1976-06-24,Tarpon Springs,Florida,USA,Puerto Rico,213.0,111.0,NaN
112319,113575,Chris Kaman,1982-04-28,Wyoming,Michigan,USA,Germany,213.0,122.0,NaN
112366,113622,Dwight Howard,1985-12-08,Atlanta,Georgia,USA,United States,211.0,120.0,NaN
118573,120309,Al-Farouq Aminu,1990-09-21,Atlanta,Georgia,USA,Nigeria,211.0,98.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
132188,135037,Domantas Sabonis,1996-05-03,Portland,Oregon,USA,Lithuania,211.0,109.0,NaN
133332,136271,DeAndre Jordan,1988-07-21,Houston,Texas,USA,United States,211.0,120.0,NaN
142044,145640,Jahlil Okafor,1995-12-15,Fort Smith,Arkansas,USA,Nigeria,211.0,NaN,NaN
142930,146560,Mike Tobey,1994-10-10,Monroe,New York,USA,Slovenia,213.0,NaN,NaN
143712,147367,JaVale McGee,1988-01-19,Flint,Michigan,USA,United States,213.0,NaN,NaN

## String Operations with `str`

Pandas provides the `str` accessor to perform string operations on a Series.

The `str` accessor allows us to apply string methods to every value in a column without using loops.

### Common String Methods

| Method | Description |
|----------|-------------|
| `str.lower()` | Converts text to lowercase |
| `str.upper()` | Converts text to uppercase |
| `str.title()` | Converts text to title case |
| `str.strip()` | Removes leading and trailing whitespace |
| `str.replace()` | Replaces specified text |
| `str.contains()` | Checks if a string contains a pattern |
| `str.startswith()` | Checks if a string starts with a pattern |
| `str.endswith()` | Checks if a string ends with a pattern |
| `str.len()` | Returns the length of each string |

### Example

```python
coffee["Coffee Type"].str.upper()
```

This converts all values in the `Coffee Type` column to uppercase.

---

## Using `str.contains()`

The `str.contains()` method checks whether each string in a column contains a specified pattern.

It returns a Boolean Series containing `True` and `False` values.

### Syntax

```python
Series.str.contains(pattern)
```

### Example

```python
coffee["Coffee Type"].str.contains("Latte")
```

Output:

```python
0     True
1    False
2     True
3    False
dtype: bool
```

---

### Filtering Rows with `str.contains()`

Since `str.contains()` returns a Boolean Series, it can be used with `loc[]` to filter rows.

```python
coffee.loc[
    coffee["Coffee Type"].str.contains("Latte")
]
```

This returns all rows where the `Coffee Type` column contains the word `"Latte"`.

---

### Case-Insensitive Search

```python
coffee.loc[
    coffee["Coffee Type"].str.contains("latte", case=False)
]
```

This matches `"Latte"`, `"LATTE"`, `"latte"`, and other case variations.

---

### Matching Multiple Patterns

```python
coffee.loc[
    coffee["Coffee Type"].str.contains("Latte|Espresso")
]
```

This returns rows where the `Coffee Type` contains either `"Latte"` or `"Espresso"`.

> **Note:** Most string operations in Pandas are performed using the `str` accessor. It allows string methods to be applied efficiently to an entire column at once.

In [ ]:
bios[bios['name'].str.contains('Keith')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

## Using `isin()`

The `isin()` method is used to check whether each value in a column exists in a specified list of values.

It returns a Boolean Series containing `True` and `False` values.

### Syntax

```python
Series.isin(values)
```

### Example

```python
coffee["Coffee Type"].isin(["Latte", "Espresso"])
```

Output:

```python
0     True
1    False
2     True
3    False
dtype: bool
```

This checks whether each value in the `Coffee Type` column is either `"Latte"` or `"Espresso"`.

---

### Filtering Rows with `isin()`

Since `isin()` returns a Boolean Series, it can be used with `loc[]` to filter rows.

```python
coffee.loc[
    coffee["Coffee Type"].isin(["Latte", "Espresso"])
]
```

This returns all rows where the `Coffee Type` is either `"Latte"` or `"Espresso"`.

---

### Using `isin()` with Multiple Values

```python
coffee.loc[
    coffee["Day"].isin(["Monday", "Wednesday", "Friday"])
]
```

This returns all rows where the `Day` is Monday, Wednesday, or Friday.

---

### Excluding Values

We can use the `~` operator to select rows that do **not** match the specified values.

```python
coffee.loc[
    ~coffee["Coffee Type"].isin(["Latte", "Espresso"])
]
```

This returns all rows where the `Coffee Type` is neither `"Latte"` nor `"Espresso"`.

> **Note:** `isin()` is often more readable and efficient than combining multiple equality conditions with the `|` (OR) operator.

In [ ]:
bios[bios.born_country.isin(['USA','FRA'])]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

## Using `query()`

The `query()` method allows us to filter rows using a string expression instead of Boolean indexing.

### Example

```python
coffee.query("`Coffee Type` == 'Latte'")
```

This returns all rows where the `Coffee Type` is `"Latte"`.

### Multiple Conditions

```python
coffee.query("`Units Sold` > 50 and `Coffee Type` == 'Latte'")
```

This returns rows where:

- `Units Sold` is greater than 50, and
- `Coffee Type` is `"Latte"`.

> **Note:** `query()` can make filtering expressions more readable, especially when working with multiple conditions.

In [ ]:
bios.query('height_cm>180')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN
25,26,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145465,149192,Stanislav Galiyev,1992-01-17,Moskva (Moscow),Moskva,RUS,ROC,188.0,82.0,NaN
145466,149193,Mikkel Aagaard,1995-10-18,Frederikshavn,Nordjylland,DEN,Denmark,184.0,81.0,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145473,149200,Toms Andersons,1993-11-25,Rīga,Rīga,LAT,Latvia,185.0,86.0,NaN
145494,149221,George Wright,1890-07-21,Toronto,Ontario,CAN,Canada,183.0,NaN,1973-01-28

  # Adding and Removing Columns

In [65]:
coffee=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/a45fad77f8791a639f0de52a7b169cb65a1482a2/warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

## Adding Columns

A new column can be added by assigning values to a new column name.

### Example

```python
coffee["price"] = 4.99
```

This creates a new column named `price` and assigns the value `4.99` to every row.

### Conditional Columns

We can create a column based on a condition using `np.where()`.

```python
import numpy as np

coffee["new_price"] = np.where(
    coffee["Coffee Type"] == "Latte",
    3.99,
    5.99
)
```

This assigns:

- `3.99` if the coffee type is `"Latte"`
- `5.99` otherwise

In [ ]:
coffee['price']=4.99
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [6]:
import numpy as np

In [7]:
coffee['new_price']=np.where(coffee['Coffee Type']=='Latte',3.99,5.99)

In [ ]:
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso          25   4.99       5.99
1     Monday       Latte          15   4.99       3.99
2    Tuesday    Espresso          30   4.99       5.99
3    Tuesday       Latte          20   4.99       3.99
4  Wednesday    Espresso          35   4.99       5.99


## Removing Columns

We can remove one or more columns using the `drop()` method.

```python
coffee.drop(columns=["price"])
```

To permanently remove the column:

```python
coffee = coffee.drop(columns=["price"])
```

Or:

```python
coffee.drop(columns=["price"], inplace=True)
```

In [ ]:
coffee.drop(0)

          Day Coffee Type  Units Sold  price  new_price
1      Monday       Latte          15   4.99       3.99
2     Tuesday    Espresso          30   4.99       5.99
3     Tuesday       Latte          20   4.99       3.99
4   Wednesday    Espresso          35   4.99       5.99
5   Wednesday       Latte          25   4.99       3.99
6    Thursday    Espresso          40   4.99       5.99
7    Thursday       Latte          30   4.99       3.99
8      Friday    Espresso          45   4.99       5.99
9      Friday       Latte          35   4.99       3.99
10   Saturday    Espresso          45   4.99       5.99
11   Saturday       Latte          35   4.99       3.99
12     Sunday    Espresso          45   4.99       5.99
13     Sunday       Latte          35   4.99       3.99

In [ ]:
coffee.drop(columns=['price'])

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       5.99
1      Monday       Latte          15       3.99
2     Tuesday    Espresso          30       5.99
3     Tuesday       Latte          20       3.99
4   Wednesday    Espresso          35       5.99
5   Wednesday       Latte          25       3.99
6    Thursday    Espresso          40       5.99
7    Thursday       Latte          30       3.99
8      Friday    Espresso          45       5.99
9      Friday       Latte          35       3.99
10   Saturday    Espresso          45       5.99
11   Saturday       Latte          35       3.99
12     Sunday    Espresso          45       5.99
13     Sunday       Latte          35       3.99

## Understanding the `axis` Parameter

Many Pandas methods use the `axis` parameter to specify whether an operation should be performed on rows or columns.

- `axis=0` → Rows (operate down the rows)
- `axis=1` → Columns (operate across the columns)

### Example: Dropping Columns

```python
coffee.drop("price", axis=1)
```

This removes the `price` column because `axis=1` refers to columns.

### Example: Dropping Rows

```python
coffee.drop(0, axis=0)
```

This removes the row with index `0` because `axis=0` refers to rows.

### Easy Way to Remember

- `axis=0` → Vertical direction ↓ (Rows)
- `axis=1` → Horizontal direction → (Columns)

> **Note:** Many Pandas methods now provide more explicit parameters such as `columns=` and `index=`, which are often easier to read than using `axis`.

In [ ]:
coffee.drop("Day",axis=1)

   Coffee Type  Units Sold
0     Espresso          25
1        Latte          15
2     Espresso          30
3        Latte          20
4     Espresso          35
5        Latte          25
6     Espresso          40
7        Latte          30
8     Espresso          45
9        Latte          35
10    Espresso          45
11       Latte          35
12    Espresso          45
13       Latte          35

## The `inplace` Parameter

The `inplace=True` parameter modifies the original DataFrame directly instead of returning a new one.

### Example

```python
coffee.drop(columns=["price"], inplace=True)
```

This permanently removes the `price` column from `coffee`.

> **Note:** When using `inplace=True`, there is no need to assign the result back to the DataFrame.

In [ ]:
coffee=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/a45fad77f8791a639f0de52a7b169cb65a1482a2/warmup-data/coffee.csv')
coffee['price']=4.99
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [ ]:
coffee.drop(columns=["price"], inplace=True)

### `copy()` Method

The `copy()` method creates an independent copy of a DataFrame. Changes made to the copied DataFrame do not affect the original DataFrame.

```python
coffee_copy = coffee.copy()
coffee_copy["price"] = 10
```

The `price` column in `coffee_copy` becomes `10`, while the original `coffee` DataFrame still contains the original prices.

In [11]:
coffee['revenue']=coffee['Units Sold']*coffee['new_price'] #Performing mathematical operations on columns
coffee.head()

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       5.99   149.75
1     Monday       Latte          15       3.99    59.85
2    Tuesday    Espresso          30       5.99   179.70
3    Tuesday       Latte          20       3.99    79.80
4  Wednesday    Espresso          35       5.99   209.65

### `rename()` Method

The `rename()` method is used to change column or index names in a DataFrame.

```python
coffee_renamed = coffee.rename(columns={"price": "Price"})

coffee_renamed.head()
```

**Output:**

The column name `price` is changed to `Price`, while the original `coffee` DataFrame remains unchanged.

In [12]:
coffee.rename(columns={'new_price':'price'})
coffee.head()

         Day Coffee Type  Units Sold  new_price  revenue
0     Monday    Espresso          25       5.99   149.75
1     Monday       Latte          15       3.99    59.85
2    Tuesday    Espresso          30       5.99   179.70
3    Tuesday       Latte          20       3.99    79.80
4  Wednesday    Espresso          35       5.99   209.65

In [13]:
bios=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/a45fad77f8791a639f0de52a7b169cb65a1482a2/data/bios.csv')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

### `to_datetime()` Method

The `to_datetime()` method converts a column or data into a datetime format.

```python
import pandas as pd

coffee["Date"] = pd.to_datetime([
    "2024-01-01",
    "2024-01-02",
    "2024-01-03",
    "2024-01-04",
    "2024-01-05"
])

coffee.head()
```

The `Date` column is converted from strings to datetime objects, making it easier to perform date and time operations.

In [23]:
bios['born_datetime']=pd.to_datetime(bios['born_date'])

In [24]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17

In [25]:
bios.info() #We can see that the `Date` column is of `datetime64[ns]` data type after applying the `pd.to_datetime()` method.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 12.2+ MB

In [26]:
bios['born_year']=bios['born_datetime'].dt.year # Extracts year from the datetime column
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0

### `format` Argument in `pd.to_datetime()`

The `format` argument specifies the format of the date strings, helping Pandas convert them correctly and efficiently.

```python
coffee["Date"] = pd.to_datetime(
    coffee["Date"],
    format="%d-%m-%Y"
)
```

Here:
- `%d` → Day
- `%m` → Month
- `%Y` → Year

For example, `"25-12-2024"` is converted to a datetime object using the specified format.

In [31]:
bios['formatted_date']=pd.to_datetime(bios['born_date'],format='%Y-%m-%d')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,formatted_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0,1878-04-17

### `to_csv()` Method

The `to_csv()` method is used to save a DataFrame as a CSV file.

```python
coffee.to_csv("coffee_data.csv", index=False)
```

This saves the `coffee` DataFrame to a file named `coffee_data.csv`. The `index=False` argument prevents row indices from being written to the CSV file.

In [32]:
bios.to_csv('bios.csv',index=False)

### `apply()` Method

The `apply()` method is used to apply a function to each value in a column.

```python
bios["name_upper"] = bios["name"].apply(str.upper)

bios[["name", "name_upper"]].head()
```

This creates a new column `name_upper` containing the athlete names in uppercase.

In [34]:
bios['height_category']=bios['height_cm'].apply(lambda x: 'Short' if x<165 else ('Average' if x<180 else 'Tall'))
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,formatted_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,1886-12-12,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,1969-04-01,Tall
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0,1898-08-13,Tall
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0,1895-05-11,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0,1878-04-17,Tall

### `apply()` Method with a User-Defined Function

You can also pass a predefined function to `apply()`.

```python
def categorize_birth_year(year):
    if year >= 1900:
        return "20th Century"
    else:
        return "19th Century"

bios["birth_century"] = bios["born_year"].apply(categorize_birth_year)

bios[["born_year", "birth_century"]].head()
```

This applies the `categorize_birth_year()` function to each value in the `born_year` column and creates a new column called `birth_century`.

In [35]:
def categorize_birth_year(year):
    if year >= 1900:
        return "20th Century"
    else:
        return "19th Century"

bios["birth_century"] = bios["born_year"].apply(categorize_birth_year)

bios[["born_year", "birth_century"]].head()

   born_year birth_century
0     1886.0  19th Century
1     1969.0  20th Century
2     1898.0  19th Century
3     1895.0  19th Century
4     1878.0  19th Century

# Merging & Concatenating Data

In [46]:
nocs=pd.read_csv('./noc_regions.csv')
nocs.head()

#https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results?select=noc_regions.csv (Kaggle link to download dataset)

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

### `merge()` Method

The `merge()` method is used to combine two DataFrames based on a common column.

```python
bios_new = pd.merge(
    bios,
    nocs,
    on="NOC",
    how="left"
)

bios_new.head()
```

This performs a left join on the `NOC` column, adding the corresponding `region` and `notes` information from the `nocs` DataFrame to the `bios` DataFrame.

In [61]:
bios_new = pd.merge(bios,nocs,on='NOC',how='left')
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,formatted_date,height_category,birth_century,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12,1886.0,1886-12-12,Tall,19th Century,NaN,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01,1969.0,1969-04-01,Tall,20th Century,NaN,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13,1898.0,1898-08-13,Tall,19th Century,NaN,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11,1895.0,1895-05-11,Average,19th Century,NaN,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17,1878.0,1878-04-17,Tall,19th Century,NaN,NaN

### `concat()` Method

The `concat()` method is used to combine two or more DataFrames along rows or columns.

```python
USA = bios[bios["NOC"] == "USA"].copy()
GBR = bios[bios["NOC"] == "GBR"].copy()

new_df = pd.concat([USA, GBR])

new_df.head()
```

This combines the rows from the `USA` and `GBR` DataFrames into a single DataFrame called `new_df`.

In [60]:
USA=bios[bios['born_country']=='USA'].copy()
GBR=bios[bios['born_country']=='GBR'].copy()
new_df=pd.concat([USA,GBR])
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime,born_year,formatted_date,height_category,birth_century
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,1967-07-22,1967.0,1967-07-22,Average,20th Century
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,1968-09-17,1968.0,1968-09-17,Average,20th Century
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,1973-10-03,1973.0,1973-10-03,Short,20th Century
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,1897-07-01,1897.0,1897-07-01,Tall,19th Century
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,1975-01-06,1975.0,1975-01-06,Average,20th Century

In [114]:
coffee=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/a45fad77f8791a639f0de52a7b169cb65a1482a2/warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

# Handling Null Values

### NumPy `np.nan`

`np.nan` (Not a Number) is used to represent missing or undefined values in a dataset.

```python
import numpy as np

coffee.loc[0, "Units Sold"] = np.nan

coffee.head()
```

This replaces the value in the `` column of the first row with a missing value (`NaN`).

In [115]:
import numpy as np

coffee.loc[0:3, "Units Sold"] = np.nan

coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso         NaN
1     Monday       Latte         NaN
2    Tuesday    Espresso         NaN
3    Tuesday       Latte         NaN
4  Wednesday    Espresso        35.0

In [68]:
coffee.info() # info() tells you the non-null count for each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   10 non-null     float64
dtypes: float64(1), object(2)
memory usage: 468.0+ bytes

### `isna()` and `sum()` Methods

The `isna()` method identifies missing (`NaN`) values, and `sum()` counts them.

```python
coffee.isna().sum()
```

This displays the number of missing values in each column of the `coffee` DataFrame.

In [116]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     4
dtype: int64

In [117]:
coffee['price']=np.where(coffee['Coffee Type']=='Latte',3.99,5.99)

### `fillna()` Method

The `fillna()` method is used to replace missing (`NaN`) values with a specified value.

```python
coffee['Units Sold'].fillna(100)
```

This replaces missing values in the `price` column with the average price of all coffee products.

In [118]:
coffee['Units Sold'].fillna(100)

0     100.0
1     100.0
2     100.0
3     100.0
4      35.0
5      25.0
6      40.0
7      30.0
8      45.0
9      35.0
10     45.0
11     35.0
12     45.0
13     35.0
Name: Units Sold, dtype: float64

In [119]:
coffee.loc[0:2,'price']=np.nan
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso         NaN    NaN
1     Monday       Latte         NaN    NaN
2    Tuesday    Espresso         NaN    NaN
3    Tuesday       Latte         NaN   3.99
4  Wednesday    Espresso        35.0   5.99

### `mean()` Method

The `mean()` method is used to calculate the average value of a numeric column.

```python
coffee["price"].mean()
```

This returns the average price of all coffee products in the `price` column.

In [79]:
coffee["price"].mean()

np.float64(4.89909090909091)

In [111]:
coffee.loc[[0,1],'Units Sold']=15
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso   15.000000    NaN
1     Monday       Latte   15.000000    NaN
2    Tuesday    Espresso         NaN    NaN
3    Tuesday       Latte   28.333333   3.99
4  Wednesday    Espresso   35.000000   5.99

### `interpolate()` Method

The `interpolate()` method is used to fill missing (`NaN`) values by estimating them from the surrounding data.

This fills missing values in the `price` column using linear interpolation based on nearby prices.

In [112]:
coffee["Units Sold"].interpolate()
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso   15.000000    NaN
1     Monday       Latte   15.000000    NaN
2    Tuesday    Espresso         NaN    NaN
3    Tuesday       Latte   28.333333   3.99
4  Wednesday    Espresso   35.000000   5.99

### `dropna()` Method

The `dropna()` method is used to remove rows or columns that contain missing (`NaN`) values.


This removes all rows in the `coffee` DataFrame that contain one or more missing values.

In [121]:
coffee.dropna()

          Day Coffee Type  Units Sold  price
4   Wednesday    Espresso        35.0   5.99
5   Wednesday       Latte        25.0   3.99
6    Thursday    Espresso        40.0   5.99
7    Thursday       Latte        30.0   3.99
8      Friday    Espresso        45.0   5.99
9      Friday       Latte        35.0   3.99
10   Saturday    Espresso        45.0   5.99
11   Saturday       Latte        35.0   3.99
12     Sunday    Espresso        45.0   5.99
13     Sunday       Latte        35.0   3.99

In [123]:
coffee.dropna(subset=['price'])

          Day Coffee Type  Units Sold  price
3     Tuesday       Latte         NaN   3.99
4   Wednesday    Espresso        35.0   5.99
5   Wednesday       Latte        25.0   3.99
6    Thursday    Espresso        40.0   5.99
7    Thursday       Latte        30.0   3.99
8      Friday    Espresso        45.0   5.99
9      Friday       Latte        35.0   3.99
10   Saturday    Espresso        45.0   5.99
11   Saturday       Latte        35.0   3.99
12     Sunday    Espresso        45.0   5.99
13     Sunday       Latte        35.0   3.99

# Aggregating Data

In [124]:
bios=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/a45fad77f8791a639f0de52a7b169cb65a1482a2/data/bios.csv')
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

### `value_counts()` Method

The `value_counts()` method is used to count the occurrences of each unique value in a column.


This displays the number of times each coffee type appears in the `coffee` DataFrame.

In [125]:
bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [127]:
bios[bios['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Massachusetts            530
Pennsylvania             530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

### `groupby()` Method

The `groupby()` method is used to group rows based on one or more columns and perform aggregate operations on each group.

```python
coffee.groupby("Coffee Type")["Units Sold"].sum()
```

This groups the data by `Coffee Type` and calculates the total number of units sold for each coffee type.

In [130]:
coffee.groupby("Coffee Type")['Units Sold'].suum()

Coffee Type
Espresso    210.0
Latte       160.0
Name: Units Sold, dtype: float64

### `agg()` Method

The `agg()` method is used to apply one or more aggregate functions to a DataFrame or grouped data.

```python
coffee.groupby("Coffee Type")["Units Sold"].agg(["sum", "mean", "max"])
```

This groups the data by `Coffee Type` and calculates the total, average, and maximum units sold for each coffee type.

In [131]:
coffee.groupby(["Coffee Type"])["Units Sold"].agg(["sum", "mean", "max"])

               sum  mean   max
Coffee Type
Espresso     210.0  42.0  45.0
Latte        160.0  32.0  35.0

### Using a Dictionary with `agg()`

A dictionary can be passed to the `agg()` method to apply different aggregate functions to different columns.

```python
coffee.groupby("Coffee Type").agg({
    "Units Sold": "sum",
    "price": "mean"
})
```

In this example:

- `Units Sold` → `sum()` is applied
- `price` → `mean()` is applied

This allows multiple columns to be aggregated using different functions in a single operation.

In [133]:
coffee.groupby("Coffee Type").agg({"Units Sold": "sum", "price": "mean"})

             Units Sold  price
Coffee Type
Espresso          210.0   5.99
Latte             160.0   3.99

In [134]:
coffee.groupby(["Coffee Type","Day"]).agg({"Units Sold": "sum", "price": "mean"})

                       Units Sold  price
Coffee Type Day
Espresso    Friday           45.0   5.99
            Monday            0.0    NaN
            Saturday         45.0   5.99
            Sunday           45.0   5.99
            Thursday         40.0   5.99
            Tuesday           0.0    NaN
            Wednesday        35.0   5.99
Latte       Friday           35.0   3.99
            Monday            0.0    NaN
            Saturday         35.0   3.99
            Sunday           35.0   3.99
            Thursday         30.0   3.99
            Tuesday           0.0   3.99
            Wednesday        25.0   3.99

In [135]:
coffee=pd.read_csv('')

         Day Coffee Type  Units Sold  price
0     Monday    Espresso         NaN    NaN
1     Monday       Latte         NaN    NaN
2    Tuesday    Espresso         NaN    NaN
3    Tuesday       Latte         NaN   3.99
4  Wednesday    Espresso        35.0   5.99

In [137]:
coffee=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/a45fad77f8791a639f0de52a7b169cb65a1482a2/warmup-data/coffee.csv')
coffee['price']=np.where(coffee['Coffee Type']=='Latte',3.99,5.99)
coffee['revenue']=coffee['Units Sold']*coffee['price']
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   5.99   149.75
1     Monday       Latte          15   3.99    59.85
2    Tuesday    Espresso          30   5.99   179.70
3    Tuesday       Latte          20   3.99    79.80
4  Wednesday    Espresso          35   5.99   209.65

### `count()` Method

The `count()` method is used to count the number of non-missing (`NaN`) values in a DataFrame or column.

```python
coffee["Units Sold"].count()
```

This returns the number of non-null values in the `Units Sold` column.

In [140]:
coffee["Units Sold"].count()

np.int64(14)

### `pivot()` Method

The `pivot()` method reshapes data by converting unique values from one column into separate columns.

```python
coffee.pivot(columns="Coffee Type",index="Day",values="revenue")
```

This creates a table where each row represents a day, each column represents a coffee type, and the values show the number of units sold.

In [139]:
pivot=coffee.pivot(columns="Coffee Type",index="Day",values="revenue")

Coffee Type  Espresso   Latte
Day
Friday         269.55  139.65
Monday         149.75   59.85
Saturday       269.55  139.65
Sunday         269.55  139.65
Thursday       239.60  119.70
Tuesday        179.70   79.80
Wednesday      209.65   99.75

### `shift()` Method

The `shift()` method moves the values in a column up or down by a specified number of positions.

```python
coffee["Previous Sales"] = coffee["Units Sold"].shift(1)
coffee.head()
```

This creates a new column containing the previous row's `Units Sold` value.

In [141]:
coffee["Previous Sales"] = coffee["Units Sold"].shift(1)
coffee.head()

         Day Coffee Type  Units Sold  price  revenue  Previous Sales
0     Monday    Espresso          25   5.99   149.75             NaN
1     Monday       Latte          15   3.99    59.85            25.0
2    Tuesday    Espresso          30   5.99   179.70            15.0
3    Tuesday       Latte          20   3.99    79.80            30.0
4  Wednesday    Espresso          35   5.99   209.65            20.0

### `rank()` Method

The `rank()` method assigns a rank to values in a column based on their order.

```python
coffee["Sales Rank"] = coffee["Units Sold"].rank(ascending=False)
coffee.head()
```

This ranks the coffee sales from highest to lowest, where the highest `Units Sold` value receives rank 1.

> **Note:** `rank()` returns decimal values by default because tied values are assigned the average of their ranks. For example, if two values share ranks 2 and 3, both receive a rank of 2.5.

In [153]:
bios['height_rank']=bios['height_cm'].rank() # Assigns ranks to heights in ascending order (shortest = rank 1, tallest = highest rank)
bios.sort_values(['height_rank'])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN,1.5
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN,1.5
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN,3.0
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN,4.5
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN,4.5
...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,NaN

In [ ]:
bios['height_rank']=bios['height_cm'].rank(ascending=False) # Assigns ranks to heights in descendibg order (tallest = rank 1, shortest = highest rank)
bios.sort_values(['height_rank'])

### `rolling()` Method

The `rolling()` method is used to perform calculations over a moving window of values.

```python
coffee["3-Day Avg Sales"] = coffee["Units Sold"].rolling(3).mean()

coffee.head()
```

This calculates the 3-row moving average of the `Units Sold` column.
### Understanding a Moving Window

A moving window is a fixed-size group of consecutive rows that moves through the data one row at a time.

For example, if `Units Sold` contains:

```text
25
15
30
20
35
```

Using:

```python
coffee["Units Sold"].rolling(3).mean()
```

Pandas first takes the first 3 values (`25, 15, 30`) and calculates their average. Then the window moves down by one row and uses (`15, 30, 20`), and so on.

```text
Window 1: [25, 15, 30] → 23.33
Window 2: [15, 30, 20] → 21.67
Window 3: [30, 20, 35] → 28.33
```

This technique is commonly used to analyze trends and smooth out fluctuations in data.

In [154]:
coffee["3-Day Avg Sales"] = coffee["Units Sold"].rolling(3).mean()
coffee.head()

,Day,Coffee Type,Units Sold,price,revenue,Previous Sales,Sales Rank,3-Day Avg Sales
0,Monday,Espresso,25,5.99,149.75,NaN,11.5,NaN
1,Monday,Latte,15,3.99,59.85,25.0,14.0,NaN
2,Tuesday,Espresso,30,5.99,179.70,15.0,9.5,23.333333
3,Tuesday,Latte,20,3.99,79.80,30.0,13.0,21.666667
4,Wednesday,Espresso,35,5.99,209.65,20.0,6.5,28.333333

### Pandas `cumsum()` Method

The `cumsum()` method calculates the cumulative sum of values in a column.

```python
coffee["Cumulative Sales"] = coffee["Units Sold"].cumsum()

coffee.head()
```

This creates a new column that shows the running total of `Units Sold`.

In [155]:
coffee["Cumulative Sales"] = coffee["Units Sold"].cumsum()

coffee.head()

,Day,Coffee Type,Units Sold,price,revenue,Previous Sales,Sales Rank,3-Day Avg Sales,Cumulative Sales
0,Monday,Espresso,25,5.99,149.75,NaN,11.5,NaN,25
1,Monday,Latte,15,3.99,59.85,25.0,14.0,NaN,40
2,Tuesday,Espresso,30,5.99,179.70,15.0,9.5,23.333333,70
3,Tuesday,Latte,20,3.99,79.80,30.0,13.0,21.666667,90
4,Wednesday,Espresso,35,5.99,209.65,20.0,6.5,28.333333,125